version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_service
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage

  app:
    build: .
    ports:
      - "7860:7860"
    environment:
      GRADIO_SERVER_NAME: 0.0.0.0
      GRADIO_SERVER_PORT: 7860
      QDRANT_HOST: qdrant_service
      QDRANT_PORT: 6333
    depends_on:
      - qdrant
    volumes:
      - .:/app

configs:
  qdrant_config:
    content: |
      log_level: INFO